name: Kotlin Android CI

# Disable Actions for now
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
